### ISSUE TITLE
HiveError: Cannot read, unknown typeId: 71. 

### ISSUE THREAD

**Issue by kasyrm** [llfbandit/dio_cache_interceptor#100]
Hi, I'm using dio_cache_interceptor with HiveCacheStore in my flutter app. I noticed that for a small amount of users we are getting the following error: 'HiveError: HiveError: Cannot read, unknown typeId: 71. Did you forget to register an adapter?'

It complains about typeId 71, 145 and 35. But from what I can see HiveCacheStore only uses 93, 94 and 95. 

I am not using Hive for anything else and not registering my own adapters anywhere. 

Hive is initialized in main like this: `await Hive.initFlutter();`

Stack trace:
```
binary_reader_impl.dart in BinaryReaderImpl.read at line 325:11 within hive
binary_reader_impl.dart in BinaryReaderImpl.readEncrypted at line 342:24 within hive
binary_reader_impl.dart in BinaryReaderImpl.readFrame at line 278:26 within hive
storage_backend_vm.dart in StorageBackendVm.readValue.<fn> at line 111:30 within hive
Called from: <asynchronous suspension>
lazy_box_impl.dart in LazyBoxImpl.get at line 32:19 within hive
Called from: <asynchronous suspension>
dio_cache_interceptor_hive_store.dart in HiveCacheStore.clean at line 49:20 within dio_cache_interceptor_hive_store
```
I would appreciate any help with finding out what might be causing it.

**Comment by llfbandit** [comment]
You're right, internal adapters are using only 93, 94 and 95 as identifiers since store creation.

I don't see how this could occur, maybe a backward compatibilty issue at some point...
Even in hive package, I can't retrieve those identifiers. Anyway, you can't recover from this error.
The only thing I could suggest is to remove the current datastore on your next release to recreate it. It's only cache data after all.
