### ISSUE TITLE
Caching POST requests and processing them later

### ISSUE THREAD

**Issue by k00na** [llfbandit/dio_cache_interceptor#48]
Hey, there 👋

This library is great for automagically handling caching of get requests, I'm already using it for that an I'm super satisfied. But where I'm having trouble is figuring out how to cache post requests and what does this library offer for caching post requests ❓🤷‍♂️

**Here's what my app needs:**
When my apps users are offline they still need to be able to fill up certain forms and save them so that once the device is back online the cached POST requests should be processed and sent trough DIO. 

**What I already know**
I'm aware that this library has `allowPostMethod` that can be set to `true` and that you have to over-ride the `keyBuilder` for making custom keys on POST requests. 

**My question**
Do you have to write your own mechanism or is this library itself able to provide an automatical queue mechanism for processing cached post requests? If so, are there any examples of that?

Thanks in advance for your time and care :)

**Comment by llfbandit** [comment]
Thanks for posting this (detailed) issue!

Yes, in POST requests I can't know what part is absolutely needed to generate a unique ID for the request (and be able to recover it).
Depending of your needs, it could be a single header, the entire body or both.

So instead of making a heavy process to embrace all use cases, the only solution is to let you make your own builder (to fine tune performance mostly) on this point.

For your needs, this package won't help you to list all the offline requests to be processed because **cache purpose is only about responses** and generic HTTP cache like your favorite web client do (remember the popup when you're going back in your history with POST request).
This is really important, allowing POST requests has been done to cover some specific use cases like SOAP WS, GraphQL and so on... But requests are never cached only their responses (with few hints on request to be exact).

When you need offline usage of an app with writes during that period time you must implement your own algorithm which can not be generic most of the time.

So, I suggest you to serialize those requests in a persistent storage with a key like you could make with this package and replay them when your back online. As far as I know, you're not in the situation of crossed data between your calls, maybe only chronology concerns...

**Comment by k00na** [comment]
Hey, thanks for clearifying!  Now I know I can focus on building my own request queue.
