### ISSUE TITLE
Why Nullable?

### ISSUE THREAD

**Issue by Reprevise** [llfbandit/dio_cache_interceptor#60]
I'm pretty confused about the implementation of a `Nullable` class when Dart has null-safety built in. 

Also, assuming this package is using semantic versioning (it should be considering Dart recommends it for all packages, breaking changes should really be a major or at least a minor version bump, not a patch bump (as described [here](https://semver.org/)).

**Comment by llfbandit** [comment]
Because, while null safety is great, we can't decern if the parameter has been given or not. In both cases, we get a null value.
So I wrapped types with `Nullable` to workaround this and to make it clear also when calling `copyWith`.

Of course, you're right about SemVer, well... I made a choice considering that was so tiny to not involve a major release and re-publish all packages. Maybe I was I tired and lazy too last night 😌

**Comment by Reprevise** [comment]
Thanks for the explanation.
