### ISSUE TITLE
allow async database path 

### ISSUE THREAD

**Issue by clragon** [llfbandit/dio_cache_interceptor#90]
To facilitate the synchronous creation of a `DbCacheStore` and in turn of a `Dio` instance plus the cache interceptor,
it would be nice to allow passing the database path as an asynchronous callback.

The problem is that the path my database would normally be located at is from `path_provider`,
and therefore must be gotten asynchronously.

The future database path callback can be synchronously resolved inside of the interceptor code by using a `LazyDatabase` in `db_os.dart`.

something like to the following:
```dart
DioCacheDatabase openDb({
  required Future<String> Function() databasePath,
  required String databaseName,
  bool logStatements = false,
}) {
  return LazyDatabase(() async {
    String path = await databasePath();
    Directory(path).createSync(recursive: true);
    final dbFile = File(p.join(databasePath, '$databaseName.db'));

    return DioCacheDatabase(
      NativeDatabase(dbFile, logStatements: logStatements),
    );
  });
}
```

the downside of this is that we now cannot pass a normal string as path anymore.

To have a nice outwards facing API, perhaps `DbCacheStore` could have a secondary named constructor (something like `DbCacheStore.lazy`) that allows passing an async callback for the database path. the normal constructor that allows a string would then redirect to this one.

**Comment by llfbandit** [comment]
Thanks for the suggestion.
Unfortunatly, this does not resolve anything on your side. You will still need to wait for the path of the DB to set the store of the interceptor. Also, this enforces CacheOptions to allow Future<CacheStore>too.
Un-waiting it will cause troubles and won't result in improvements since your application needs to handle store initialization errors.

**Comment by clragon** [comment]
I am not sure I can follow what youre saying.
Why would I need to await the store or the cache options?
`LazyDatabase` is resolved by drift itself, we can use it fully synchronously all the way.
the interceptor does not need to await any futures and neither does the user.

**Comment by llfbandit** [comment]
I understand but what about the others developers.

Let's take an example by lazying all the stores initialization. First request is made, the store is not ready, init will launch and fails. From here we can't recover properly or nicely because the interceptor is already setup and added to Dio.
That's what I want to avoid, a fuzzy behaviour on how the package works when trying to keep simple usage.

I already get so many SOS questions as issues that I don't want to expand it further.

I'll think about this twice but...

**Comment by clragon** [comment]
ah, the problem would be with other stores that cannot lazily initialize without awaiting a future.
in that case I will close this issue.
