### ISSUE TITLE
Etag cache control Issue 

### ISSUE THREAD

**Issue by FrancoisBontemps** [llfbandit/dio_cache_interceptor#96]
Hi, 

I'm trying to use the Etag header for Cache control, but i can't make it working. 

My first call respond me this : 
![Screenshot 2022-11-15 at 12 13 12](https://user-images.githubusercontent.com/47889038/201906250-7451307f-26a6-406e-b179-d54942c52de5.png)

And my dio cache interceptor config is like that: 
![Screenshot 2022-11-15 at 12 15 42](https://user-images.githubusercontent.com/47889038/201906381-c4b29a7d-03eb-4487-bc0d-e85a860bc8c9.png)

But i'm always receiving response with status 200 even if my Etag is equal to the previous call (tried it on postamn). I'have tried several configurations. Maybe it's because of the received cache-control, or because of interceptors superposition...

Any ideas ?

**Comment by llfbandit** [comment]
Yes, `max-age=0` directive makes your response expired on the second call, this is the same as `must-revalidate` directive (`max-age=0` is often set to be compatible with older HTTP clients).

On the second call `ETag` and `If-Modified-Since` should be set by the interceptor to check the freshness of the first response.
From here, you should already get a status 304 with headers only.

Like you said, postman gives the same result, the issue seems to be not related with the package at this stage.
Did you properly setup the cache mecanism on your origin server?

**Comment by FrancoisBontemps** [comment]
I'm not responsible for the cache mecanism on the server but now i have some solid element of response to give ! 
Thanks a lot, i'm closing this issue
